### ISSUE TITLE
Feedback: Running OpenCV as an AWS Lambda Function

### ISSUE THREAD

**Issue by iandow** [iandow/iandow.github.io#14]

**Comment by arynh** [comment]
Hello, when I attempt to build the docker image `lambda-layer-factory`, I get the following error: `docker: Error response from daemon: pull access denied for lambda-layer-factory, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.` I'm logged in on the docker daemon, so is this image private, or should I be looking for another issue?

**Comment by iandow** [comment]
I'm not sure what's up there. Make sure you're following the instructions on https://github.com/iandow/opencv_aws_lambda instead of the blog post, and if you still get that error then try building another amazonlinux docker image from a simplified Dockerfile.

**Comment by arutaki** [comment]
Hi, I get the error `  file /usr/lib64/libpython3.so from install of python36-libs-3.6.8-2.el7.ius.x86_64 conflicts with file from package python3-libs-3.7.4-1.amzn2.0.3.x86_64` when I wanted to build the docker file.  Do you have any advise for this issue?

**Comment by iandow** [comment]
Could you please copy and paste your output from the `docker build
--tag=lambda-layer-factory:latest .`  into a Github gist file and share the
link to the gist file here?

**Comment by iandow** [comment]
@arutaki I was able to reproduce your issue. I think I fixed it with an update to the Dockerfile. Can you see if this update fixes your issue?

**Comment by arutaki** [comment]
Yes, I can now build the Dockerfile just fine. Thanks.

**Comment by h3nryh3nry** [comment]
Hi! Thanks for the great article.

Just to let you know - the command to copy generated zip file can fail under Windows + git-bash console:

```$ docker run --rm -it -v $(pwd):/data python-opencv-factory cp /packages/cv2-python36.zip /data```
the input device is not a TTY.  If you are using mintty, try prefixing the command with 'winpty'

**Comment by Adoom666** [comment]
just a quick note, wrap quotes around the "$(pwd):/data" part if there's spaces in your path 🤦🏻‍♂️

docker run --rm -it -v "$(pwd):/data" python-opencv-factory cp /packages/cv2-python36.zip /data
